name: Night Test Execution Android

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-tests-android:
    name: Run Tests on Android
    uses: ahttps://github.com/erikmenini/handoff_automation/.github/workflows/reusable_e2e_flow.yml@develop
    with:
      ambiente: DEV
      platform: Android
      execution_type: DAILY
      app_version: latest
    secrets: inherit
